"""Общие словари: страны, флаги, русские города, вместимость бортов."""

# ── Country flags (используется для Telegram-сообщений) ──────────────────
COUNTRY_FLAGS = {
    'Russia': '🇷🇺', 'China': '🇨🇳', 'India': '🇮🇳', 'UAE': '🇦🇪', 'Singapore': '🇸🇬',
    'Malaysia': '🇲🇾', 'Indonesia': '🇮🇩', 'Thailand': '🇹🇭', 'Vietnam': '🇻🇳', 'South Korea': '🇰🇷',
    'Japan': '🇯🇵', 'Australia': '🇦🇺', 'New Zealand': '🇳🇿', 'UK': '🇬🇧', 'Germany': '🇩🇪',
    'France': '🇫🇷', 'Italy': '🇮🇹', 'Spain': '🇪🇸', 'Netherlands': '🇳🇱', 'Turkey': '🇹🇷',
    'Saudi Arabia': '🇸🇦', 'Qatar': '🇶🇦', 'Kuwait': '🇰🇼', 'Oman': '🇴🇲', 'Bahrain': '🇧🇭',
    'Jordan': '🇯🇴', 'Israel': '🇮🇱', 'Kazakhstan': '🇰🇿', 'Uzbekistan': '🇺🇿', 'Azerbaijan': '🇦🇿',
    'Armenia': '🇦🇲', 'Georgia': '🇬🇪', 'Kyrgyzstan': '🇰🇬', 'Tajikistan': '🇹🇯', 'Turkmenistan': '🇹🇲',
    'Pakistan': '🇵🇰', 'Bangladesh': '🇧🇩', 'Sri Lanka': '🇱🇰', 'Nepal': '🇳🇵', 'Cambodia': '🇰🇭',
    'Myanmar': '🇲🇲', 'Laos': '🇱🇦', 'Brunei': '🇧🇳', 'Hong Kong': '🇭🇰', 'Taiwan': '🇹🇼',
    'Macau': '🇲🇴', 'Maldives': '🇲🇻', 'Greece': '🇬🇷', 'Poland': '🇵🇱', 'Czechia': '🇨🇿',
    'Austria': '🇦🇹', 'Hungary': '🇭🇺', 'Latvia': '🇱🇻', 'Estonia': '🇪🇪', 'Finland': '🇫🇮',
    'Sweden': '🇸🇪', 'Norway': '🇳🇴', 'Denmark': '🇩🇰', 'Switzerland': '🇨🇭', 'Portugal': '🇵🇹',
    'Ukraine': '🇺🇦', 'Belarus': '🇧🇾', 'Lithuania': '🇱🇹', 'Moldova': '🇲🇩', 'Bulgaria': '🇧🇬',
    'Romania': '🇷🇴', 'Serbia': '🇷🇸', 'Croatia': '🇭🇷', 'Slovenia': '🇸🇮', 'Slovakia': '🇸🇰',
    'Luxembourg': '🇱🇺', 'Ireland': '🇮🇪', 'Iceland': '🇮🇸', 'Cyprus': '🇨🇾', 'Malta': '🇲🇹',
}

# ── IATA → Country mapping ────────────────────────────────────────────────
MAP_C = {
    'SVO':'Russia','DME':'Russia','VKO':'Russia','LED':'Russia','KZN':'Russia','SVX':'Russia','OVB':'Russia',
    'KJA':'Russia','AER':'Russia','KRR':'Russia','ROV':'Russia','UFA':'Russia','MRV':'Russia','STW':'Russia',
    'ASF':'Russia','EIK':'Russia','KGD':'Russia','GOJ':'Russia','KUF':'Russia','NAL':'Russia','MQF':'Russia',
    'TJM':'Russia','NJC':'Russia','SGC':'Russia','HTA':'Russia','BQS':'Russia','DYR':'Russia','IKT':'Russia',
    'VVO':'Russia','KHV':'Russia','PKC':'Russia','UUS':'Russia','GDX':'Russia','YKS':'Russia','BTK':'Russia',
    'PEZ':'Russia','SCW':'Russia','USY':'Russia','VKT':'Russia','IJK':'Russia','OGZ':'Russia','MCX':'Russia',
    'GRV':'Russia','ESL':'Russia','VKZ':'Russia','KLF':'Russia','BZK':'Russia','KGP':'Russia',
    'ALA':'Kazakhstan','NQZ':'Kazakhstan','KGF':'Kazakhstan','GUW':'Kazakhstan','SCO':'Kazakhstan',
    'PLX':'Kazakhstan','PWQ':'Kazakhstan','URA':'Kazakhstan','AKX':'Kazakhstan','KSN':'Kazakhstan',
    'CIT':'Kazakhstan','DMB':'Kazakhstan','UKK':'Kazakhstan','ZHA':'Kazakhstan',
    'PEK':'China','PVG':'China','CAN':'China','SZX':'China','CTU':'China','HAK':'China','XIY':'China',
    'CKG':'China','WUH':'China','NKG':'China','TAO':'China','XMN':'China','CGO':'China','CSX':'China',
    'DLC':'China','TSN':'China','KMG':'China','NNG':'China','KWL':'China','FOC':'China','HGH':'China',
    'WNZ':'China','JJN':'China','LYA':'China','SWA':'China','TNA':'China','YNT':'China','ZUH':'China',
    'NGB':'China','CGQ':'China','HRB':'China','SJW':'China','TYN':'China','URC':'China','LHW':'China',
    'HFE':'China','KWE':'China','CGD':'China','YIH':'China','XFN':'China','MXZ':'China',
    'JHG':'China','LJG':'China','DLU':'China','XSY':'China','WUX':'China',
    'DEL':'India','BOM':'India','BLR':'India','MAA':'India','HYD':'India','CCU':'India','GOI':'India',
    'AMD':'India','PNQ':'India','JAI':'India','LKO':'India','GAU':'India','TRV':'India','IXC':'India',
    'COK':'India','STV':'India','VNS':'India','IXB':'India','IXR':'India','IXM':'India','VTZ':'India',
    'IXZ':'India','JRH':'India','DMU':'India','IXW':'India','RPR':'India','BBI':'India','BHO':'India',
    'UDR':'India','IDR':'India','NAG':'India','RAJ':'India','BDQ':'India','IXJ':'India','SXR':'India',
    'DXB':'UAE','AUH':'UAE','SHJ':'UAE','DOH':'Qatar','KWI':'Kuwait','RUH':'Saudi Arabia','JED':'Saudi Arabia',
    'DMM':'Saudi Arabia','BAH':'Bahrain','MCT':'Oman','AMM':'Jordan','TLV':'Israel','BEY':'Lebanon',
    'LHR':'UK','MAN':'UK','LGW':'UK','STN':'UK','FRA':'Germany','MUC':'Germany','DUS':'Germany','BER':'Germany',
    'CDG':'France','ORY':'France','FCO':'Italy','MXP':'Italy','VCE':'Italy','AMS':'Netherlands','MAD':'Spain',
    'BCN':'Spain','VIE':'Austria','PRG':'Czechia','WAW':'Poland','BUD':'Hungary','RIX':'Latvia','TLL':'Estonia',
    'HEL':'Finland','ARN':'Sweden','CPH':'Denmark','OSL':'Norway','ZRH':'Switzerland','GVA':'Switzerland',
    'LIS':'Portugal','ATH':'Greece','SIN':'Singapore','KUL':'Malaysia','PEN':'Malaysia','HKG':'Hong Kong',
    'TPE':'Taiwan','ICN':'South Korea','GMP':'South Korea','NRT':'Japan','HND':'Japan','KIX':'Japan',
    'SYD':'Australia','MEL':'Australia','BNE':'Australia','PER':'Australia','AKL':'New Zealand','CHC':'New Zealand',
    'TAS':'Uzbekistan','SKD':'Uzbekistan','NVI':'Uzbekistan','UGC':'Uzbekistan',
    'GYD':'Azerbaijan','NAJ':'Azerbaijan',
    'EVN':'Armenia',
    'FRU':'Kyrgyzstan','OSS':'Kyrgyzstan',
    'DYU':'Tajikistan','LBD':'Tajikistan','KQT':'Tajikistan',
    'ASB':'Turkmenistan','CRZ':'Turkmenistan','MYP':'Turkmenistan',
    'TBS':'Georgia','BUS':'Georgia','KUT':'Georgia',
    'KIV':'Moldova',
    'MLE':'Maldives','SGN':'Vietnam','HAN':'Vietnam','PNH':'Cambodia','RGN':'Myanmar','DPS':'Indonesia',
    'JOG':'Indonesia','SUB':'Indonesia','UPG':'Indonesia','REP':'Cambodia','DAC':'Bangladesh','KHI':'Pakistan',
    'CMB':'Sri Lanka','KTM':'Nepal','ISB':'Pakistan','LHE':'Pakistan','PEW':'Pakistan','MUX':'Pakistan',
    'CJU':'South Korea','PUS':'South Korea','FUK':'Japan','OKA':'Japan','NGO':'Japan','BKK':'Thailand',
    'DMK':'Thailand','CNX':'Thailand','USM':'Thailand','HDY':'Thailand','KBV':'Thailand','TST':'Thailand',
    'NAW':'Thailand','THS':'Thailand','UBP':'Thailand','CEI':'Thailand','NST':'Thailand','URT':'Thailand',
    'HHQ':'Thailand','CJM':'Thailand','KCH':'Malaysia','BKI':'Malaysia','TGG':'Malaysia','SDK':'Malaysia',
    'BWN':'Brunei','MFM':'Macau','VTE':'Laos','LPQ':'Laos','MDL':'Myanmar','NYU':'Myanmar','HEH':'Myanmar',
    'VCA':'Vietnam','PQC':'Vietnam','CXR':'Vietnam','DAD':'Vietnam','UIH':'Vietnam','VKG':'Vietnam','DLI':'Vietnam',
    'KOS':'Cambodia','HRI':'Sri Lanka','RML':'Sri Lanka','TRR':'Sri Lanka','PKR':'Nepal','BIR':'Nepal',
    'TKG':'Indonesia','PDG':'Indonesia','PKU':'Indonesia','BTH':'Indonesia','TNJ':'Indonesia','PLM':'Indonesia',
    'KBP':'Ukraine','ODS':'Ukraine','HRK':'Ukraine','DNK':'Ukraine','IEV':'Ukraine','LWO':'Ukraine',
    'MSQ':'Belarus','GME':'Belarus','VNO':'Lithuania','KUN':'Lithuania','LPX':'Latvia','URE':'Estonia',
    'TMP':'Finland','TKU':'Finland','OUL':'Finland','KUO':'Finland','RVN':'Finland','GOT':'Sweden','MMX':'Sweden',
    'BLL':'Denmark','AAL':'Denmark','RKE':'Denmark','BGO':'Norway','TRD':'Norway','SVG':'Norway','TOS':'Norway',
    'BSL':'Switzerland','BRN':'Switzerland','LUG':'Switzerland','OPO':'Portugal','FAO':'Portugal','FNC':'Portugal',
    'SKG':'Greece','HER':'Greece','RHO':'Greece','CFU':'Greece','ZTH':'Greece','IST':'Turkey','SAW':'Turkey',
    'ADB':'Turkey','AYT':'Turkey','ESB':'Turkey','DLM':'Turkey','BJV':'Turkey','TZX':'Turkey','KYA':'Turkey'
}

# ── Russian airport IATA → Russian city name ─────────────────────────────
MAP_RU_CITY = {
    'SVO': 'Москва', 'DME': 'Москва', 'VKO': 'Москва',
    'LED': 'Санкт-Петербург',
    'KZN': 'Казань',
    'SVX': 'Екатеринбург',
    'OVB': 'Новосибирск',
    'KJA': 'Красноярск',
    'AER': 'Сочи',
    'KRR': 'Краснодар',
    'ROV': 'Ростов-на-Дону',
    'UFA': 'Уфа',
    'MRV': 'Минеральные Воды',
    'STW': 'Ставрополь',
    'ASF': 'Астрахань',
    'EIK': 'Ейск',
    'KGD': 'Калининград',
    'GOJ': 'Нижний Новгород',
    'KUF': 'Самара',
    'NAL': 'Нальчик',
    'MQF': 'Магнитогорск',
    'TJM': 'Тюмень',
    'NJC': 'Нижневартовск',
    'SGC': 'Сургут',
    'HTA': 'Чита',
    'BQS': 'Благовещенск',
    'DYR': 'Анадырь',
    'IKT': 'Иркутск',
    'VVO': 'Владивосток',
    'KHV': 'Хабаровск',
    'PKC': 'Петропавловск-Камчатский',
    'UUS': 'Южно-Сахалинск',
    'GDX': 'Магадан',
    'YKS': 'Якутск',
    'BTK': 'Братск',
    'PEZ': 'Пенза',
    'SCW': 'Сыктывкар',
    'USY': 'Усинск',
    'VKT': 'Воркута',
    'IJK': 'Ижевск',
    'OGZ': 'Владикавказ',
    'MCX': 'Махачкала',
    'GRV': 'Грозный',
    'ESL': 'Элиста',
    'VKZ': 'Великий Новгород',
    'KLF': 'Калуга',
    'BZK': 'Брянск',
    'KGP': 'Когалым',
}

# ── Aircraft IATA → seat capacity ─────────────────────────────────────────
CAP = {
    '319':140,'320':180,'321':220,'332':280,'333':320,'339':350,'359':325,'388':525,
    '737':180,'738':189,'739':220,'73J':220,'772':314,'773':365,'77W':396,'77L':314,
    '788':250,'789':290,'78J':330,
    '32A':180,'32B':186,'32N':186,'32Q':186,'32S':180,
    'E90':100,'E95':120,'CR9':90,'DH4':78,'AT7':70,'CRJ':90,
}
LOAD_FACTOR = 0.82  # средняя загрузка международных рейсов (Аз.-Тихоокеанский регион)

# ── RU month/day names (для Telegram/дашборда) ──────────────────────────
MONTH_NAMES_RU = {1:'Янв',2:'Фев',3:'Мар',4:'Апр',5:'Май',6:'Июн',
                  7:'Июл',8:'Авг',9:'Сен',10:'Окт',11:'Ноя',12:'Дек'}
DAY_NAMES_RU   = {0:'Пн',1:'Вт',2:'Ср',3:'Чт',4:'Пт',5:'Сб',6:'Вс'}

# ── Domestic airport sets по странам ─────────────────────────────────────
DOMESTIC_TH = {'BKK','DMK','CNX','USM','HDY','UTP','KBV','TST','NAW','THS','UBP','CEI','NST','URT','HHQ','CJM'}

DOMESTIC_VN = {'SGN','HAN','DAD','HPH','VDH','VII','DIN','DLI','PQC','BMV','UIH','VCL','VCS','TBB','VKG','VCA','XPY','CAH','PXU','VDO','VCM'}
